### ISSUE TITLE
Download True PDF

### ISSUE THREAD

**Issue by nickdrones** [Bishalsarang/Pearson-PDF-Downloader#2]
You said you had a way to download the true PDF of the ebook but it was password protected. I have a way to remove the password from a zip file or pdf file. Is there any way you would be able to tell us how you download the true pdf?

**Comment by Bishalsarang** [comment]
I don't have access to Pearson library now, so I can't test it right now.

But what I noticed while I was trying to download true pdf was you can intercept request or observe in network requests the URL that lead to the location of zip file.
I think I've already deleted the zipped file too because it was a while ago. 
Try intercepting the requests and you may be able to download the zip file consisting of a pdf file and epub file which is, unfortunately, password protected.

If you have access to the library maybe I can try what lead me to the zip file.
