### ISSUE TITLE
Something has changed the images won't download anymore

### ISSUE THREAD

**Issue by LudovicBouvierJohnston** [Bishalsarang/Pearson-PDF-Downloader#3]
Hello, I  have problem where the images won't download in the folder. The script fails with out of range because the list is empty. I tried with this book and it doesn't work for some reason. Thanks in advance :) 

The book id is `2fd5434c-c348-4a76-a387-60d89abd829c`

**Comment by Bishalsarang** [comment]
@LudovicBouvierJohnston 

The downloader is still working I think. I tested it for the _book id_ : `562732ef-51b2-4486-ba35-0fe26dcbeaa8` and it works fine

But for some reason, the book id you gave is not working.
You can easily check this URL  [https://d38l3k3yaet8r2.cloudfront.net/resources/products/epubs/generated/`562732ef-51b2-4486-ba35-0fe26dcbeaa8`/foxit-assets/pages/page0?password=&accessToken=null&formMode=true](https://d38l3k3yaet8r2.cloudfront.net/resources/products/epubs/generated/562732ef-51b2-4486-ba35-0fe26dcbeaa8/foxit-assets/pages/page0?password=&accessToken=null&formMode=true) downloads the cover of the book

But if you replace the book id in the same URL :  [https://d38l3k3yaet8r2.cloudfront.net/resources/products/epubs/generated/`2fd5434c-c348-4a76-a387-60d89abd829c`/foxit-assets/pages/page0?password=&accessToken=null&formMode=true](https://d38l3k3yaet8r2.cloudfront.net/resources/products/epubs/generated/2fd5434c-c348-4a76-a387-60d89abd829c/foxit-assets/pages/page0?password=&accessToken=null&formMode=true) it doesn't download any image.

So the issue may be because they changed this URL pattern or the book id may be wrong.
Unfortunately, I don't have access to the Pearson library anymore. So I cannot check and verify it myself.
If you have the library credentials then you may find how they are rendering each pages and we may possibly find the solution.
